
CREATE TABLE IF NOT EXISTS `international_phonecode` (
  `cn_name` varchar(50) DEFAULT NULL,
  `en_name` varchar(50) DEFAULT NULL,
  `code` varchar(50) DEFAULT NULL,
  `countryiso` varchar(50) DEFAULT NULL,
  `continent` varchar(50) DEFAULT NULL,
  `call_prefix` varchar(50) DEFAULT NULL,
  `support_esurfing` varchar(50) DEFAULT NULL
);


INSERT INTO `international_phonecode` (`cn_name`, `en_name`, `code`, `countryiso`, `continent`, `call_prefix`,`support_esurfing`) VALUES
('中文名称', '英文名称', '长途区号', '缩写', '大洲', '长途字冠','是否支持'),
('阿富汗', 'Afghanistan', '93', 'AF', '8', '00','Y'),
('阿尔巴尼亚', 'Albania', '355', 'AL', '3', NULL,'Y'),
('安道尔', 'Andorra', '376', 'AD', '3', NULL,'Y'),
('安哥拉', 'Angola', '244', 'AO', '2', NULL,'N'),
('安提瓜和巴布达', 'Antigua and Barbuda', '1268', 'AG', '1', '011','N'),
('阿根廷', 'Argentina', '54', 'AR', '5', NULL,'Y'),
('阿鲁巴', 'Aruba', '297', 'AW', '2', NULL,'N'),
('澳大利亚', 'Australia', '61', 'AU', '6', '0011','N'),
('奥地利', 'Austria', '43', 'AT', '3', NULL,'Y'),
('阿塞拜疆', 'Azerbaijan', '944', 'AZ', '8', NULL,'Y'),
('巴林', 'Bahrain', '973', 'BH', '8', NULL,'Y'),
('孟加拉国', 'Bangladesh', '880', 'BD', '8', NULL,'Y'),
('巴巴多斯', 'Barbados', '1246', 'BB', '1', '011','N'),
('白俄罗斯', 'Belarus', '375', 'BY', '3', '8~10','Y'),
('比利时', 'Belgium', '32', 'BE', '3', NULL,'Y'),
('伯利兹', 'Belize', '501', 'BZ', '5', NULL,'N'),
('贝宁', 'Benin', '229', 'BJ', '2', NULL,'Y'),
('百慕大', 'Bermuda', '1441', 'BM', '1', '011','N'),
('不丹', 'Bhutan', '975', 'BT', '8', NULL,'N'),
('玻利维亚', 'Bolivia', '591', 'BO', '5', '0010','Y'),
('亚美尼亚', 'Armenia', '374', 'AM', '8', NULL,'Y'),
('波斯尼亚和黑塞哥维那', 'Bosnia and Herzegovina', '387', 'BA', '3', NULL,'Y'),
('博茨瓦纳', 'Botswana', '267', 'BW', '2', NULL,'Y'),
('布维岛', 'Bouvet Island', '', 'BV', NULL, NULL,'N'),
('巴西', 'Brazil', '55', 'BR', '5', '00xx','Y'),
('英属印度洋领地', 'British Indian Ocean Territory', '', 'IO', NULL, NULL,'N'),
('英属维尔京群岛', 'British Virgin Islands', '1284', 'BVI', '6', '011','N'),
('文莱', 'Brunei Darussalam', '673', 'BN', '8', NULL,'Y'),
('保加利亚', 'Bulgaria', '359', 'BG', '3', NULL,'N'),
('布基纳法索', 'Burkina Faso', '226', 'BF', '2', NULL,'Y'),
('布隆迪', 'Burundi', '257', 'BI', '2', '90','Y'),
('柬埔寨', 'Cambodia', '855', 'KH', '8', NULL,'N'),
('喀麦隆', 'Cameroon', '237', 'CM', '2', NULL,'Y'),
('加拿大', 'Canada', '1', 'CA', '1', '011','Y'),
('佛得角', 'Cape Verde', '238', 'CV', '2', NULL,'Y'),
('开曼群岛', 'Cayman Islands', '1345', 'KY', '1', '011','N'),
('中非共和国', 'Central African Republic', '236', 'CF', '2', '19','Y'),
('乍得', 'Chad', '235', 'TD', '2', '15','N'),
('智利', 'Chile', '56', 'CL', '5', '1xx0','Y'),
('中国', 'China', '86', 'CN', '8', NULL,'N'),
('哥伦比亚', 'Colombia', '57', 'CO', '5', '005','N'),
('科摩罗', 'Comoros', '269', 'KM', '2', NULL,'N'),

('哥斯达黎加', 'Costa Rica', '506', 'CR', '5', NULL,'N'),
('科特迪瓦', 'Cote d''Ivoire', '225', 'CI', '2', NULL,'N'),
('克罗地亚', 'Croatia', '385', 'HR', '3', NULL,'Y'),
('古巴', 'Cuba', '53', 'CU', '1', '119','N'),
('塞浦路斯', 'Cyprus', '357', 'CY', '3', NULL,'Y'),
('捷克', 'Czech Republic', '420', 'CZ', '3', NULL,'Y'),
('丹麦', 'Denmark', '45', 'DK', '3', NULL,'Y'),
('吉布提', 'Djibouti', '253', 'DJ', '2', NULL,'N'),
('多米尼克', 'Dominica', '1767', 'DM', '1', '011','Y'),
('法罗群岛', 'Faroe Islands', '298', 'FO', '3', NULL,'Y'),
('厄瓜多尔', 'Ecuador', '593', 'EC', '5', NULL,'N'),
('埃及', 'Egypt', '20', 'EG', '2', NULL,'Y'),
('萨尔瓦多', 'El Salvador', '503', 'SV', '5', NULL,'N'),
('赤道几内亚', 'Equatorial Guinea', '240', 'GQ', '2', NULL,'Y'),
('厄立特里亚', 'Eritrea', '291', 'ER', '2', NULL,'Y'),
('爱沙尼亚', 'Estonia', '372', 'EE', '3', NULL,'N'),
('埃塞俄比亚', 'Ethiopia', '251', 'ET', '2', NULL,'N'),
('欧盟', 'European Union', '', NULL, NULL, NULL,'N'),
('安圭拉', 'Anguilla', '1264', 'AI', '3', '011','N'),
('芬兰', 'Finland', '358', 'FI', '3', '99','Y'),
('法国', 'France', '33', 'FR', '3', NULL,'N'),
('阿尔及利亚', 'Algeria', '213', 'DZ', '3', '00~','Y'),
('法属波利尼西亚', 'French Polynesia', '689', 'PF', '3', NULL,'N'),
('法属南部领土', 'French Southern and Antarctic Lands', '', NULL, NULL, NULL,'N'),
('加蓬', 'Gabon', '241', 'GA', '2', NULL,'N'),
('格鲁吉亚', 'Georgia', '995', 'GE', '8', NULL,'N'),
('德国', 'Germany', '49', 'DE', '3', NULL,'N'),
('加纳', 'Ghana', '233', 'GH', '2', NULL,'Y'),
('直布罗陀', 'Gibraltar', '1', 'GI', '3', NULL,'Y'),
('希腊', 'Greece', '30', 'GR', '3', NULL,'Y'),
('格林纳达', 'Grenada', '1473', 'GD', '1', '011','N'),
('瓜德罗普', 'Guadeloupe', '590', 'GP', '3', NULL,'Y'),
('关岛', 'Guam', '1671', 'GU', '3', '011','Y'),
('危地马拉', 'Guatemala', '502', 'GT', '6', NULL,'N'),
('根西岛', 'Guernsey', '1481', NULL, '1', NULL,'N'),
('几内亚', 'Guinea', '224', 'GN', '2', NULL,'Y'),
('几内亚比绍', 'Guinea-Bissau', '245', 'GW', '2', NULL,'N'),
('法属圭亚那', 'French Guiana', '594', 'GF', '3', NULL,'Y'),
('海地', 'Haiti', '509', 'HT', '5', NULL,'N'),
('赫德岛和麦克唐纳岛', 'Heard Island and McDonald Islands', '', 'HM', NULL, NULL,'N'),
('洪都拉斯', 'Honduras', '504', 'HN', '5', NULL,'N'),
('中国香港', 'Hong Kong (SAR)', '852', 'HK', '8', '001','N'),
('匈牙利', 'Hungary', '36', 'HU', '3', NULL,'N'),
('冰岛', 'Iceland', '354', 'IS', '3', NULL,'N'),
('印度', 'India', '91', 'IN', '8', NULL,'N'),
('印度尼西亚', 'Indonesia', '62', 'ID', '8', '001','N'),
('伊朗', 'Iran', '98', 'IR', '8', NULL,'Y'),
('伊拉克', 'Iraq', '964', 'IQ', '8', NULL,'Y'),
('爱尔兰', 'Ireland', '353', 'IE', '3', NULL,'Y'),
('以色列', 'Israel', '972', 'IL', '8', '01x','Y'),
('意大利', 'Italy', '39', 'IT', '3', NULL,'N'),
('萨摩亚', 'Samoa', '685', 'WS', '6', NULL,'N'),
('日本', 'Japan', '81', 'JP', '8', '010','Y'),
('泽西岛', 'Jersey', '', NULL, NULL, NULL,'N'),
('约旦', 'Jordan', '962', 'JO', '8', NULL,'Y'),
('哈萨克斯坦', 'Kazakhstan', '7', 'KZ', '8', '8~10','N'),
('肯尼亚', 'Kenya', '254', 'KE', '2', '000','Y'),
('韩国', 'Korea, South', '82', 'KP', '8', '001','N'),
('科威特', 'Kuwait', '965', 'KW', '8', NULL,'Y'),
('吉尔吉斯斯坦', 'Kyrgyzstan', '996', 'KG', '8', NULL,'N'),
('老挝', 'Laos', '856', 'LA', '8', NULL,'Y'),
('拉脱维亚', 'Latvia', '371', 'LV', '3', NULL,'Y'),
('黎巴嫩', 'Lebanon', '961', 'LB', '8', NULL,'Y'),
('莱索托', 'Lesotho', '266', 'LS', '2', NULL,'N'),
('利比里亚', 'Liberia', '231', 'LR', '2', NULL,'N'),
('利比亚', 'Libya', '218', 'LY', '2', NULL,'Y'),
('列支敦士登', 'Liechtenstein', '423', 'LI', '3', NULL,'N'),
('立陶宛', 'Lithuania', '370', 'LT', '3', NULL,'Y'),
('卢森堡', 'Luxembourg', '352', 'LU', '3', NULL,'N'),
('中国澳门', 'Macao', '853', 'MO', '8', NULL,'N'),
('马其顿', 'Macedonia, The Former Yugoslav Republic of', '389', 'MK', '3', NULL,'Y'),
('马达加斯加', 'Madagascar', '261', 'MG', '2', NULL,'Y'),
('马拉维', 'Malawi', '265', 'MW', '2', NULL,'Y'),
('马来西亚', 'Malaysia', '60', 'MY', '8', NULL,'N'),
('马尔代夫', 'Maldives', '960', 'MV', '8', NULL,'Y'),
('马里', 'Mali', '223', 'ML', '2', NULL,'N'),
('马恩岛', 'Man, Isle of', '', NULL, NULL, NULL,'N'),
('马提尼克', 'Martinique', '596', 'MQ', '3', NULL,'Y'),

('毛里塔尼亚', 'Mauritania', '222', 'MR', '2', NULL,'Y'),
('毛里求斯', 'Mauritius', '230', 'MU', '2', '0x0','Y'),
('墨西哥', 'Mexico', '52', 'MX', '1', NULL,'N'),

('摩尔多瓦', 'Moldova', '373', 'MD', '3', NULL,'Y'),
('摩纳哥', 'Monaco', '377', 'MC', '3', NULL,'N'),
('蒙特塞拉特', 'Montserrat', '1664', 'MS', '1', '011','N'),
('摩洛哥', 'Morocco', '212', 'MA', '2', '00~','N'),
('莫桑比克', 'Mozambique', '258', 'MZ', '2', NULL,'Y'),
('纳米尼亚', 'Namibia', '264', 'NA', '2', NULL,'Y'),
('瑙鲁', 'Nauru', '674', 'NR', '6', NULL,'N'),
('尼泊尔', 'Nepal', '977', 'NP', '8', NULL,'Y'),
('荷兰', 'Netherlands', '31', 'NL', '3', NULL,'N'),
('荷属安的列斯', 'Netherlands Antilles', '599', 'AN', '3', NULL,'N'),
('新喀里多尼亚', 'New Caledonia', '687', 'NC', '6', NULL,'N'),
('新西兰', 'New Zealand', '64', 'NZ', '6', NULL,'N'),
('尼加拉瓜', 'Nicaragua', '505', 'NI', '5', NULL,'N'),
('尼日尔', 'Niger', '227', 'NE', '2', NULL,'Y'),
('尼日利亚', 'Nigeria', '234', 'NG', '2', '009','Y'),
('挪威', 'Norway', '47', 'NO', '3', NULL,'Y'),
('阿曼', 'Oman', '968', 'OM', '8', NULL,'Y'),
('巴基斯坦', 'Pakistan', '92', 'PK', '8', NULL,'Y'),
('帕劳', 'Palau', '680', 'PW', '6', NULL,'N'),
('巴拿马', 'Panama', '507', 'PA', '5', NULL,'N'),
('巴布亚新几内亚', 'Papua New Guinea', '675', 'PG', '6', '05','N'),
('巴拉圭', 'Paraguay', '595', 'PY', '5', '002','Y'),
('秘鲁', 'Peru', '51', 'PE', '5', NULL,'Y'),
('菲律宾', 'Philippines', '63', 'PH', '8', NULL,'Y'),
('皮特凯恩', 'Pitcairn Islands', '', 'PN', '6', NULL,'N'),
('波兰', 'Poland', '48', 'PL', '3', NULL,'Y'),
('葡萄牙', 'Portugal', '351', 'PT', '3', NULL,'Y'),
('代理服务器', 'Proxy Server', '', NULL, NULL, NULL,'N'),
('波多黎各', 'Puerto Rico', '1809', 'PR', '1', '011','N'),
('卡塔尔', 'Qatar', '974', 'QA', '8', NULL,'N'),
('黑山共和国', 'Republic of Montenegro', '', NULL, NULL, NULL,'N'),
('罗马尼亚', 'Romania', '40', 'RO', '3', NULL,'Y'),
('俄罗斯', 'Russia', '7', 'RU', '3', '8~10','Y'),
('卢旺达', 'Rwanda', '250', 'RW', '2', NULL,'N'),
('圣基茨和尼维斯', 'Saint Kitts and Nevis', '1869', 'KN', '1', '011','N'),
('圣卢西亚', 'Saint Lucia', '1758', 'LC', '1', '011','N'),

('圣文森特和格林纳丁斯', 'Saint Vincent and the Grenadines', '1784', 'VC', '1', '011','N'),
('圣马力诺', 'San Marino', '378', 'SM', '3', NULL,'N'),
('沙特阿拉伯', 'Saudi Arabia', '966', 'SA', '8', NULL,'Y'),
('塞内加尔', 'Senegal', '221', 'SN', '2', NULL,'Y'),
('塞尔维亚', 'Serbia', '', NULL, NULL, NULL,'N'),
('塞尔维亚和黑山', 'Serbia and Montenegro', '381', 'CS', '3', NULL,'N'),
('塞舌尔', 'Seychelles', '248', 'SC', '2', NULL,'Y'),
('塞拉利昂', 'Sierra Leone', '232', 'SL', '2', NULL,'Y'),
('新加坡', 'Singapore', '65', 'SG', '8', '001','Y'),
('斯洛伐克', 'Slovakia', '421', 'SK', '3', NULL,'N'),
('斯洛文尼亚', 'Slovenia', '386', 'SI', '3', NULL,'N'),
('所罗门群岛', 'Solomon Islands', '677', 'SB', '6', NULL,'N'),
('索马里', 'Somalia', '252', 'SO', '2', NULL,'N'),
('南非', 'South Africa', '27', 'ZA', '2', NULL,'Y'),
('南乔治亚岛和南桑德韦奇岛', 'South Georgia and the South Sandwich Islands', '', 'GS', NULL, NULL,'N'),
('西班牙', 'Spain', '34', 'ES', '3', NULL,'N'),
('斯里兰卡', 'Sri Lanka', '94', 'LK', '8', NULL,'Y'),
('苏丹', 'Sudan', '249', 'SD', '2', NULL,'Y'),
('苏里南', 'Suriname', '597', 'SR', '5', NULL,'Y'),
('梵蒂冈', 'Holy See (Vatican City)', '3906698', 'VA', '3', NULL,'N'),
('斯威士兰', 'Swaziland', '268', 'SZ', '2', NULL,'Y'),
('瑞典', 'Sweden', '46', 'SE', '3', NULL,'Y'),
('瑞士', 'Switzerland', '41', 'CH', '3', NULL,'Y'),
('叙利亚', 'Syria', '963', 'SY', '8', NULL,'N'),
('中国台湾', 'Taiwan', '886', 'TW', '8', '002','N'),
('塔吉克斯坦', 'Tajikistan', '992', 'TJ', '8', '8~10','N'),
('坦桑尼亚', 'Tanzania', '255', 'TZ', '2', '000','Y'),
('泰国', 'Thailand', '66', 'TH', '8', '001','Y'),
('巴哈马', 'The Bahamas', '1242', 'BS', '1', '011','N'),
('冈比亚', 'The Gambia', '220', 'GM', '2', NULL,'Y'),
('美属萨摩亚', 'American Samoa', '684', 'AS', '6', '011','N'),
('汤加', 'Tonga', '676', 'TO', '6', NULL,'N'),
('特立尼达和多巴哥', 'Trinidad and Tobago', '1868', 'TT', '1', '011','Y'),
('突尼斯', 'Tunisia', '216', 'TN', '2', NULL,'Y'),
('土耳其', 'Turkey', '90', 'TR', '8', NULL,'Y'),
('土库曼斯坦', 'Turkmenistan', '993', 'TM', '8', '8~10','N'),
('阿鲁巴', 'Aruba', '297', 'AW', '5', NULL,'N'),
('乌干达', 'Uganda', '256', 'UG', '2', '000','Y'),
('乌克兰', 'Ukraine', '380', 'UA', '3', '8~10','Y'),
('阿拉伯联合酋长国', 'United Arab Emirates', '971', 'AE', '8', NULL,'Y'),
('英国', 'United Kingdom', '44', 'GB', '3', NULL,'N'),
('美国', 'United States', '1', 'US', '1', '011','Y'),
('乌拉圭', 'Uruguay', '598', 'UY', '5', NULL,'N'),
('乌兹别克斯坦', 'Uzbekistan', '998', 'UZ', '8', '8~10','Y'),
('瓦努阿图', 'Vanuatu', '678', 'VU', '6', NULL,'N'),
('委内瑞拉', 'Venezuela', '58', 'VE', '5', NULL,'N'),
('越南', 'Vietnam', '84', 'VN', '8', NULL,'Y'),
('美属维尔京群岛', 'Virgin Islands', '1340', NULL, '1', '011','N'),
('东帝汶', 'Democratic Republic of Timor-Leste', '1', 'TLS', '8', NULL,'N'),
('巴勒斯坦', 'Palestine', '970', 'BL', '8', NULL,'N'),
('根西岛', 'Guernsey', '1', 'GCI', '3', NULL,'Y'),
('曼岛', 'Mann', '1', 'SCO', '3', NULL,'N'),
('泽西岛', 'Jersey', '1', 'JCI', '3', NULL,'N'),
('格陵兰', 'Kulusuk', '299', 'KUS', '3', NULL,'N'),
('波多黎各', 'Puerto Rico', '1787', 'PR', '5', NULL,'N'),
('西撒哈拉', 'Western Sahara', '2', 'EH', NULL, NULL,'N'),
('也门', 'Yemen', '967', 'YE', '8', NULL,'N'),
('南斯拉夫', 'Yugoslavia', '', NULL, NULL, NULL,'N'),
('牙买加', 'Jamaica', '1876', 'JM', '6', '011','Y'),
('赞比亚', 'Zambia', '260', 'ZM', '2', NULL,'Y'),
('津巴布韦', 'Zimbabwe', '263', 'ZW', '2', NULL,'Y');

